### ISSUE TITLE
Megablast usage in the Filter_S4.sh 

### ISSUE THREAD

**Issue by guorongxu** [zhangch/WGSpipeline#2]
Hi Dr. Zhang,

Thank you very much for your amazing pipeline! It is awesome and really great tool!

I am trying to use your WGSpipeline to process our data and I have a megablast usage issue in your script Filter_S4.sh. I downloaded the blast-2.2.27 and I was told that megablast is one of option of blastn. But in your script Filter_S4.sh, you just directly call megablast. so I felt confusing where I can call megablast if I don't have standalone megablast. 

megablast -d $BLASTHUMANDB -a $CPU -W 16 -e 0.0000001 -v 1 -b 0 -i ${WORKDIR}/${SAMPLE}_Filter_S3.fasta -o ${WORKDIR}/${SAMPLE}_Filter_S4.out

Your response would be really appreciated!

**Comment by guorongxu** [comment]
After I built the megablast index with the below command,
makembindex -input human_genomic.fa -output human_genomic -iformat fasta

and then run the below command,
blastn -task megablast -db $BLASTHUMANDB -num_threads $CPU -num_descriptions 1 -num_alignments 1 -word_size 13 -evalue 0.0001 -query ${WORKDIR}/${SAMPLE}_Filter_S4.out

Now it works!

**Comment by zhangch** [comment]
Great! Please feel free to ask if you have any questions.
